version: '3.8'

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: database 
    ports:
      - 5433:5432
  rabbitmq:
    image: rabbitmq:3.9.20-management
    container_name: message-broker
    stdin_open: true  # docker run -i
    tty: true         # docker run -t 
    ports:
      - 15672:15672   # UI
      - 5672:5672     # pub/sub